### ISSUE TITLE
求教程解决

### ISSUE THREAD

**Issue by 123232334453** [yapeteam/OpenYolBi#6]
![bandicam 2024-11-21 19-15-17-761](https://github.com/user-attachments/assets/e7a63747-ebbb-45d1-9fa9-56fd97d8dc8c)

**Comment by TIMER-err** [comment]
这个可以不管他，是silentfix用的

**Comment by Tzsnb** [comment]
不是解决了吗

**Comment by 123232334453** [comment]
谢谢谢谢
